Avant toute chose, on commence par supprimer les données du dataset qui ne nous intéressent pas, on créé ensuite un nouveau dataset, bien plus léger, qui nous servira de base de travail pour la suite.

```{r}
####################################
### PREMIER ECREMAGE DES DONNEES ###
####################################

#Lecture du dataset original
gterror = read.csv("globalterrorismdb_0718dist.csv", sep=',', header=TRUE)
gg
#Filtrage pour ne garder que les colonnes pertinentes
filtered <- subset(gterror, select=c(iyear, imonth, extended, country_txt, region_txt, provstate, city, latitude, longitude, multiple, success, suicide, attacktype1_txt, targtype1_txt, natlty1_txt, gname, nperps, claimed, weaptype1_txt, nkill, nkillter, nwound, nwoundte))

#Renommage des colonnes 
names(filtered) <- c("année", "mois", "étendu", "pays", "région", "région_locale", "ville", "latitude", "longitude", "multiple", "succès", "suicide", "type_attaque", "cible", "nationalité_ciblée", "responsable", "nombre_terroristes", "revendiqué", "type_arme", "nombre_morts", "nombre_terroristes_morts", "nombre_blessés", "nombre_terroristes_blessés")

#Sauvegarde sur csv
write.csv(filtered, "./filtered_terrorism.csv")
```
C'est parti !
```{r}
####################################
####### COMMENCER EN DOUCEUR #######
####################################

gterror = read.csv("filtered_terrorism.csv", sep=',', header=TRUE)
require("ggplot2")
require("plyr")
```
Se familiariser avec les données :
```{r}
#Nombre de victimes du terrorisme depuis 1970 : 411868
nbkills = sum(na.omit(gterror$nombre_morts))
#Nombre de victimes du terrorisme par année : 2014 est l'année la plus meurtrière avec quasiment 45000 victimes !
killsPerYear = ddply(gterror, .(année), summarize, morts = sum(na.omit(nombre_morts)))
plot = ggplot(killsPerYear, aes(x=année,y=morts))+geom_line()+ggtitle("Evolution du nombre de victimes du terrorisme dans le monde.")+xlab("Année")+ylab("Nombre de morts")
ggsave(plot, filename = "graphiques/killsPerYear.pdf")
#Nombre de victimes du terrorisme par région du monde
killsPerRegion = killsPerYear = ddply(gterror, .(région), summarize, morts = sum(na.omit(nombre_morts)))
killsPerRegion = killsPerRegion[order(-killsPerRegion$morts),]
killsPerRegion
ggplot(killsPerRegion, aes(x=région,y=morts))+geom_bar(stat="identity")+ggtitle("Nombre de victimes du terrorisme par région")+xlab("Région")+ylab("Nombre de morts")
```
